"use strict";

const EXTRA_CONNECTOR_DEFINITIONS = [
  {
    id: "namecheap",
    label: "Namecheap",
    authType: "apiKey",
    scopes: ["domain:read", "pricing:read"],
    fields: [
      { name: "apiUser", type: "text", required: true, help: "Namecheap API user" },
      { name: "apiKey", type: "password", required: true, help: "Namecheap API key" },
      { name: "clientIp", type: "text", required: false, help: "Allowed client IP (optional)" },
    ],
    docsUrl: "https://www.namecheap.com/support/api/intro/",
  },
  {
    id: "autotrader",
    label: "Autotrader",
    authType: "apiKey",
    scopes: ["vehicles:read", "pricing:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "Autotrader partner API key" },
      { name: "partnerId", type: "text", required: false, help: "Partner identifier" },
    ],
    docsUrl: "https://developer.autotrader.com/",
  },
  {
    id: "myclickdealer",
    label: "MyClickDealer",
    authType: "apiKey",
    scopes: ["inventory:read", "dealer:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "MyClickDealer API key" },
      { name: "dealerId", type: "text", required: true, help: "Dealer identifier" },
    ],
    docsUrl: "https://www.myclickdealer.co.uk/",
  },
  {
    id: "booking",
    label: "Booking",
    authType: "apiKey",
    scopes: ["accommodations:read", "availability:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "Booking API key/token" },
      { name: "affiliateId", type: "text", required: false, help: "Affiliate identifier" },
    ],
    docsUrl: "https://developers.booking.com/",
  },
  {
    id: "skyscanner",
    label: "Skyscanner",
    authType: "apiKey",
    scopes: ["flights:read", "pricing:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "Skyscanner API key" },
      { name: "market", type: "text", required: false, help: "Market (e.g. UK, US)" },
    ],
    docsUrl: "https://developers.skyscanner.net/",
  },
  {
    id: "openai",
    label: "OpenAI",
    authType: "apiKey",
    scopes: ["responses:write", "models:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "OpenAI API key" },
      { name: "organization", type: "text", required: false, help: "Optional org/project id" },
    ],
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    id: "meta_ads",
    label: "Meta Ads",
    authType: "oauth2",
    scopes: ["ads:write", "campaigns:read"],
    fields: [
      { name: "accessToken", type: "token", required: true, help: "Meta Ads access token" },
      { name: "adAccountId", type: "text", required: true, help: "Ad account id" },
    ],
    docsUrl: "https://developers.facebook.com/docs/marketing-apis/",
  },
  {
    id: "zillow",
    label: "Zillow",
    authType: "apiKey",
    scopes: ["property:read", "valuation:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "Zillow API key/token" },
      { name: "market", type: "text", required: false, help: "Target market/ZIP" },
    ],
    docsUrl: "https://www.zillowgroup.com/developers/",
  },
  {
    id: "rightmove",
    label: "Rightmove",
    authType: "apiKey",
    scopes: ["listings:read", "valuation:read"],
    fields: [
      { name: "apiKey", type: "password", required: true, help: "Rightmove API key/token" },
      { name: "branchId", type: "text", required: false, help: "Branch identifier" },
    ],
    docsUrl: "https://www.rightmove.co.uk/",
  },
];

const STRATEGIC_WIDGET_MANIFESTS = [
  {
    widgetId: "widget_domain_valuator",
    id: "widget_domain_valuator",
    name: "Domain Valuator",
    title: "Domain Valuator",
    version: "1.0.0",
    requiredConnectors: [
      { connectorId: "fasthosts", scopes: ["domain:read", "dns:read"], fields: ["apiKey"] },
      { connectorId: "namecheap", scopes: ["domain:read", "pricing:read"], fields: ["apiUser", "apiKey"] },
    ],
    runPolicy: { serverOnly: true },
    ui: { category: "Valuation" },
    category: "Valuation",
    inputs: ["domain", "workspaceId"],
    outputs: ["valuation_summary", "connector_results"],
    actions: ["price_domain", "compare_registrar_data", "prepare_quote"],
    route: "/tools/domain-valuation-tool",
    status: "active",
  },
  {
    widgetId: "widget_car_valuator",
    id: "widget_car_valuator",
    name: "Car Valuator",
    title: "Car Valuator",
    version: "1.0.0",
    requiredConnectors: [
      { connectorId: "autotrader", scopes: ["vehicles:read", "pricing:read"], fields: ["apiKey"] },
      { connectorId: "myclickdealer", scopes: ["inventory:read", "dealer:read"], fields: ["apiKey", "dealerId"] },
    ],
    runPolicy: { serverOnly: true },
    ui: { category: "Valuation" },
    category: "Valuation",
    inputs: ["vehicle_registration", "inventory_context"],
    outputs: ["valuation_summary", "market_comparison"],
    actions: ["inspect_inventory", "price_vehicle", "generate_summary"],
    route: "/tools/car-valuation-tool",
    status: "active",
  },
  {
    widgetId: "widget_trip_finder",
    id: "widget_trip_finder",
    name: "Trip Finder",
    title: "Trip Finder",
    version: "1.0.0",
    requiredConnectors: [
      { connectorId: "booking", scopes: ["accommodations:read", "availability:read"], fields: ["apiKey"] },
      { connectorId: "skyscanner", scopes: ["flights:read", "pricing:read"], fields: ["apiKey"] },
    ],
    runPolicy: { serverOnly: true },
    ui: { category: "Finding" },
    category: "Finding",
    inputs: ["origin", "destination", "travel_dates"],
    outputs: ["itinerary_options", "pricing_summary"],
    actions: ["search_flights", "search_hotels", "rank_options"],
    route: "/tools/trip-finder",
    status: "active",
  },
  {
    widgetId: "widget_ad_generator",
    id: "widget_ad_generator",
    name: "Ad Generator",
    title: "Ad Generator",
    version: "1.0.0",
    requiredConnectors: [
      { connectorId: "openai", scopes: ["responses:write"], fields: ["apiKey"] },
      { connectorId: "meta_ads", scopes: ["ads:write", "campaigns:read"], fields: ["accessToken", "adAccountId"] },
    ],
    runPolicy: { serverOnly: true },
    ui: { category: "Marketing" },
    category: "Marketing",
    inputs: ["campaign_brief", "target_audience", "creative_constraints"],
    outputs: ["ad_copy", "campaign_plan"],
    actions: ["draft_creative", "prepare_meta_ads_payload", "review_guardrails"],
    route: "/tools/ad-generator",
    status: "active",
  },
  {
    widgetId: "widget_property_evaluator",
    id: "widget_property_evaluator",
    name: "Property Evaluator",
    title: "Property Evaluator",
    version: "1.0.0",
    requiredConnectors: [
      { connectorId: "zillow", scopes: ["property:read", "valuation:read"], fields: ["apiKey"] },
      { connectorId: "rightmove", scopes: ["listings:read", "valuation:read"], fields: ["apiKey"] },
    ],
    runPolicy: { serverOnly: true },
    ui: { category: "Valuation" },
    category: "Valuation",
    inputs: ["property_address", "market_context"],
    outputs: ["valuation_summary", "listing_comparison"],
    actions: ["inspect_property_data", "price_property", "prepare_brief"],
    route: "/tools/property-evaluator",
    status: "active",
  },
];

const SYSTEM_TOOL_MANIFESTS = [
  {
    widgetId: "vault_tool",
    id: "vault_tool",
    name: "Vault Tool",
    title: "Vault Tool",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Security" },
    category: "Security",
    inputs: ["vault_passphrase", "secret_payload", "record_filters"],
    outputs: ["secret_records", "memory_records", "audit_records"],
    actions: ["unlock_vault", "store_secret", "store_memory", "read_records"],
    route: "/tools/vault",
    status: "active",
  },
  {
    widgetId: "agent_browser",
    id: "agent_browser",
    name: "Agent Browser",
    title: "Agent Browser",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Operations" },
    category: "Operations",
    inputs: ["url", "mode", "session_snapshot"],
    outputs: ["browser_journal", "transcript_record", "handoff_request"],
    actions: ["navigate", "fallback", "handoff", "journal"],
    route: "/tools/agent-browser",
    status: "active",
  },
  {
    widgetId: "server_control",
    id: "server_control",
    name: "Server Control",
    title: "Server Control",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Security" },
    category: "Security",
    inputs: ["server_action", "approval_code", "network_scope"],
    outputs: ["server_plan", "approval_state", "server_logs"],
    actions: ["prepare_server_change", "lock_server", "restart_ssh", "emergency_close"],
    route: "/tools/server-control",
    status: "active",
  },
  {
    widgetId: "reviewer_agent",
    id: "reviewer_agent",
    name: "Reviewer Agent",
    title: "Reviewer Agent",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Security" },
    category: "Security",
    inputs: ["prompt", "task_context", "recent_actions"],
    outputs: ["reviewer_status", "conflict_report", "execution_gate"],
    actions: ["detect_duplicates", "detect_conflicts", "require_human_confirmation"],
    route: "/tools/reviewer-agent",
    status: "active",
  },
  {
    widgetId: "auto_shoot_evaluator",
    id: "auto_shoot_evaluator",
    name: "Auto-Shoot Evaluator",
    title: "Auto-Shoot Evaluator",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Operations" },
    category: "Operations",
    inputs: ["lane_a", "lane_b", "task_context"],
    outputs: ["evaluation", "selected_lane", "guardrail_summary"],
    actions: ["score_responses", "select_winner", "write_evaluation_record"],
    route: "/tools/auto-shoot-evaluator",
    status: "active",
  },
  {
    widgetId: "quotation_valuation_engine",
    id: "quotation_valuation_engine",
    name: "Quotation and Valuation",
    title: "Quotation and Valuation",
    version: "1.0.0",
    requiredConnectors: [],
    runPolicy: { serverOnly: true },
    ui: { category: "Valuation" },
    category: "Valuation",
    inputs: ["quote_brief", "valuation_type", "pricing_context"],
    outputs: ["quote_draft", "valuation_summary", "approval_ready_plan"],
    actions: ["prepare_quote", "prepare_valuation", "route_to_toolbox"],
    route: "/tools/quotation-valuation-engine",
    status: "active",
  },
];

const connectorToWidgets = () => {
  const out = new Map();
  for (const manifest of STRATEGIC_WIDGET_MANIFESTS) {
    for (const req of manifest.requiredConnectors || []) {
      const connectorId = String(req?.connectorId || "");
      if (!connectorId) continue;
      if (!out.has(connectorId)) out.set(connectorId, []);
      out.get(connectorId).push({
        widgetId: manifest.widgetId,
        name: manifest.name,
      });
    }
  }
  return out;
};

module.exports = {
  EXTRA_CONNECTOR_DEFINITIONS,
  STRATEGIC_WIDGET_MANIFESTS,
  SYSTEM_TOOL_MANIFESTS,
  connectorToWidgets,
};
